### PR TITLE
specify that some `Text.translatable` methods take a fallback

### PR DESCRIPTION
**Pull request by eristhea**
I'm personally neutral on this change, but it was suggested by @patbox. discuss!

### CODE REVIEW

**Review by EnnuiL — APPROVED** [review]
This looks fine, but I do wonder how we could simplify that name; it feels a bit too verbose for the simple pattern it is going for

**Comment by eristhea** [comment]
I spent a couple minutes thinking, but I couldn't find a simpler way to convey "make a translatable text with a fallback"

**Comment by Patbox** [comment]
For record, both yarn and mojmap use the same name

**Review by supersaiyansubtlety — APPROVED** [review]

**Comment by EnnuiL** [comment]
> For record, both yarn and mojmap use the same name

huh, that's nice to know

**Review by moehreag — APPROVED** [review]

**Review by IotaBread — APPROVED** [review]
Another alternative could be `translatableOr`, though I don't think it really fits

**Comment by EnnuiL** [comment]
> Another alternative could be `translatableOr`, though I don't think it really fits

yeah, it looks too ambiguous

**Pull request merged**
