### PR TITLE
map `TreeDecorator`'s inner class

### PR DESCRIPTION
**Pull request by eristhea**
fairly straightforward, but I'm not sure about the name of the entire class. I was considering `Generator`, but since it's replacing already existing blocks instead of generating new ones, I thought `BlockReplacer` was a good name. Please leave feedback on that specifically though!

### CODE REVIEW

**Review by OroArmor — APPROVED** [review]

**Review by IotaBread — APPROVED** [review]

**Review by triphora — APPROVED** [review]

**Comment by Kroppeb** [comment]
I personally don't like the name "BlockReplacer" at all. When it's passed as argument you call it "context" which seems to agree with my opinion.

**Review by supersaiyansubtlety — APPROVED** [review]

**Comment by eristhea** [comment]
the more I think about it the more I dislike the name
but since there's data being sent to it, I don't agree with `Context` either
@Kroppeb how would you feel about simplifying it to `Placer`?

**Comment by eristhea** [comment]
I added some javadoc and decided to go with the `Placer` name instead. I think it's a better name since this class is mostly replacing air, and the `Block` prefix felt redundant, given that the user is providing it BlockStates.

**Comment by Kroppeb** [comment]
mmh, The thing that kinda annoys me is the fact that the class doesn't really do much appart from being a wrapper around data. The only actual logic is the fact it sorts the lists and provides a utility method for placing vines. In the mean time, `Placer` doesn't convey the fact it is also used to store the roots, leaves and logs locations.

**Comment by eristhea** [comment]
exactly why I haven't been able to decide on a name, it's just such an odd class.
do you have any suggestions?

**Review by NoComment1105 — APPROVED** [review]

**Review by NoahvdAa — APPROVED** [review]
Looks good from web

**Review by AlsoSylv — APPROVED** [review]

**Pull request merged**
