### PR TITLE
Mappings for damage type tags (& Provider) & record class

### PR DESCRIPTION
**Pull request by Mysterious-Dev**
All is in the title ^^.

### CODE REVIEW

**Review by eristhea — COMMENTED** [review]
why `DamageTypeTagsProvider` over `DamageTypeTagProvider`?

**Comment by OroArmor** [comment]
Currently tag providers dont have a consistent naming scheme. Some are `Tag` while others are `Tags`

**Review by OroArmor — APPROVED** [review]

**Review by eristhea — APPROVED** [review]
I'll approve then, but I think that should be fixed in the future

**Comment by Mysterious-Dev** [comment]
I moved DamageTypeTagsProvider to `net.minecraft.data.server.tag` (instead of `net.minecraft.data.server`).

**Pull request merged**
