### PR TITLE
rename intprovider and floatprovider

### LINKED ISSUE #410: refactor all packages to use underscores instead of two consecutive words
things like `net/minecraft/util/intprovider` are bad.

todo:
- [ ] add package names to spell check
- [ ] fix all issues

(waiting on #409 before I work on this)

### PR DESCRIPTION
**Pull request by eristhea**
fixes #410

### CODE REVIEW

**Review by OroArmor — APPROVED** [review]

**Review by IotaBread — APPROVED** [review]

**Review by EnnuiL — CHANGES_REQUESTED** [review]
While I like those new names better, I do wonder if something like `providers/<type>` would be better

**Comment by LambdAurora** [comment]
Not allowed due to them being primitives.

**Comment by EnnuiL** [comment]
> Not allowed due to them being primitives.

java what in the world

**Review by EnnuiL — APPROVED** [review]
I accept defeat by Java then; This name is much much better than gluecase anyway

**Review by LambdAurora — COMMENTED** [review]
Definitely feeling a bit weird about using underscores.
But our conventions state that we should follow a specific structure and respect [Java conventions](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) which doesn't seem to disallow underscores.

But it does indicate that if you want to use `int` as a single component it should be written as `int_` which is quite worse.

**Comment by eristhea** [comment]
the arguments kinda boil down to two main points from what I've seen
- for: the separation of the words makes things more clear
- against: the underscores feel strange to people who use java a lot

I think that since our goal is readability and not familiarity, underscores are what we should go for

**Pull request merged**
