### PR TITLE
Fix a couple loot-y things

### PR DESCRIPTION
**Pull request by supersaiyansubtlety**
- rename `EntityType`'s `get/LootTableId` -> `get/LootTable`: it's not an id anymore and this matches `LivingEntity`
- map `MinecraftServer`'s `getReloadableRegistries`

### CODE REVIEW

**Review by eristhea — APPROVED** [review]
no idea what happened with the merge, it's probably easier to cherry-pick this once it's through FCP

**Review by OroArmor — APPROVED** [review]

**Comment by supersaiyansubtlety** [comment]
> no idea what happened with the merge, it's probably easier to cherry-pick this once it's through FCP

The return type of `getLootTable` methods changed to `Optional` in 24w37a.
I've fixed that and restored a couple things that got lost/dropped.

**Comment by supersaiyansubtlety** [comment]
It looks like #635 and #636 both got lost in a match or something, and this is merging them back in now.

Any idea how that happened?

**Comment by eristhea** [comment]
no, i'll see if i can fix that up tomorrow

**Pull request merged**
