### PR TITLE
fix 'overrides final method' error

### PR DESCRIPTION
**Pull request by supersaiyansubtlety**
Fixes this error which occurs on launch when using 1.21.4-build.1:
```
java.lang.IncompatibleClassChangeError: class net.minecraft.entity.InteractionEntity overrides final method net.minecraft.entity.Entity.getHeight()F
```

### CODE REVIEW

**Review by eristhea — COMMENTED** [review]
should the corresponding fields (f_luxekrhz and f_rmbogufh) be updated as well?

**Comment by supersaiyansubtlety** [comment]
> should the corresponding fields (f_luxekrhz and f_rmbogufh) be updated as well?

arguably, but their keys are just `"width"` and `"height"`

I think it's fine either way, what's your preference?

**Comment by eristhea** [comment]
personally, we should update the field names but not the key fields

**Review by eristhea — APPROVED** [review]
merging after checks!

**Pull request merged**
