### PR TITLE
Rename `ThreadedAnvilChunkStorage`

### LINKED ISSUE #6: Renaming `ThreadedAnvilChunkStorage`
I have 2 problems with TACS' current name:
1. _`Anvil`_ - this class does not deal with the Anvil chunk format at all! That's handled by `ChunkSerializer`.
2. _`Storage`_ - this class is actually a chunk _manager_, not just storage!

Additionally, there's the field that stores an instance of TACS in `ServerChunkManager`. You'll never guess what it's called... and `ServerChunkManager` delegates most of its actions to this instance (see my 2nd point)!

Therefore, I propose:
- We rename `ThreadedAnvilChunkStorage` to `ThreadedChunkManager`.
- We also rename `ServerChunkManager.threadedAnvilChunkStorage` to `ServerChunkManager.delegate`.

### PR DESCRIPTION
**Pull request by Leo40Git**
Closes #6.
This was already done (#4), but it was closed for a discussion issue that never went anywhere.

Hopefully this reignites this topic...

### CODE REVIEW

**Comment by eristhea** [comment]
failing javadocs:
```
/__w/quilt-mappings/quilt-mappings/.gradle/temp/fakeSource/net/minecraft/server/world/ThreadedChunkManager.java:971: error: reference not found
       * ticks. This is used by {@link ThreadedAnvilChunkStorage#tickEntityMovement()

/__w/quilt-mappings/quilt-mappings/.gradle/temp/fakeSource/net/minecraft/server/world/ThreadedChunkManager.java:944: error: reference not found
    * @see ThreadedAnvilChunkStorage#entityTrackers
```

**Comment by Leo40Git** [comment]
Whoops, Javadocs fixed!

**Review by eristhea — APPROVED** [review]
might be worth doing a thorough search for usages if you haven't, this diff seems quite small

**Comment by eristhea** [comment]
in `CONVENTIONS.md`, at line 182, it uses the TACS name. please fix!

**Comment by Leo40Git** [comment]
Did a quick Ctrl+Shift+F for TACS and didn't find anything (beyond that `CONVENTIONS.md` reference, oops)

**Review by OroArmor — APPROVED** [review]

**Review by IotaBread — APPROVED** [review]

**Pull request merged**
