### PR TITLE
rename placeLogsAndLeaves to updateLeavesDistances

### LINKED ISSUE #448: `TreeFeature#placeLogsAndLeaves` is a misnomer
`net.minecraft.world.gen.feature.TreeFeature#placeLogsAndLeaves` places no logs, and only replaces existing leaves states with updated distance properties.

Something like `setLeavesDistances` would be an accurate description.

### PR DESCRIPTION
**Pull request by supersaiyansubtlety**
Fixes #448

### CODE REVIEW

**Comment by LambdAurora** [comment]
Shouldn't this be update instead of set? It doesn't set a given value, it updates the values based on surroundings if I understood right

**Comment by supersaiyansubtlety** [comment]
> Shouldn't this be update instead of set? It doesn't set a given value, it updates the values based on surroundings if I understood right

**Comment by supersaiyansubtlety** [comment]
Missclicks... sorry

**Comment by supersaiyansubtlety** [comment]
> Shouldn't this be update instead of set? It doesn't set a given value, it updates the values based on surroundings if I understood right

You're right, update is better

**Review by eristhea — APPROVED** [review]

**Review by EnnuiL — APPROVED** [review]

**Review by LambdAurora — APPROVED** [review]

**Pull request merged**
