### PR TITLE
Remove redundant docs

### PR DESCRIPTION
**Pull request by supersaiyansubtlety**
Discussed [here](https://github.com/QuiltMC/quilt-mappings/pull/523#discussion_r1440047503), and again briefly [here](https://github.com/QuiltMC/quilt-mappings/pull/532#discussion_r1454042595).
Voted for [on discord](https://discord.com/channels/817576132726620200/1104011466660659273/1191965094708523038).

@OroArmor you said the color values are useful, are you in favor of keeping them?

### CODE REVIEW

**Comment by supersaiyansubtlety** [comment]
If this is agreed upon, should I add a sentence to CONVENTIONS.md#javadocs about excluding docs that don't add any information?

**Review by eristhea — APPROVED** [review]
I don't think we need to put this in conventions, as all of these are yarn holdovers

**Comment by OroArmor** [comment]
> Discussed [here](https://github.com/QuiltMC/quilt-mappings/pull/523#discussion_r1440047503), and again briefly [here](https://github.com/QuiltMC/quilt-mappings/pull/532#discussion_r1454042595).
> Voted for [on discord](https://discord.com/channels/817576132726620200/1104011466660659273/1191965094708523038).
> 
> @OroArmor you said the color values are useful, are you in favor of keeping them?

Yes. It allows people to look at the value from the javadoc.

**Comment by supersaiyansubtlety** [comment]
> > @OroArmor you said the color values are useful, are you in favor of keeping them?
> 
> Yes. It allows people to look at the value from the javadoc.

Are the colors a special case or are you generally in favor of docs whose purpose is to display literal values?

**Comment by OroArmor** [comment]
I'm pretty sure we do it for model part names as well. I think for constants it makes sense but isn't always needed.

**Comment by supersaiyansubtlety** [comment]
Yeah this PR removes the model part name ones as well.
Should we have another vote here, where more people may see it?

**Comment by supersaiyansubtlety** [comment]
Well this PR is just sitting here so I guess I'll summarize my position:
These javadocs *are not documentation*
- they repeat the information already in the source code
- they don't explain what it does or why
- they don't explain how to use it

Furthermore, they add clutter when viewing the source and create busywork for mappings contributors.
> It allows people to look at the value from the javadoc.

I don't think that's what javadocs are for.

**Comment by eristhea** [comment]
FORMAL GITHUB VOTE:

DOES THIS PR GO THROUGH? :+1: for yes, :-1: for no. this will be open for 1 week.

**Comment by lukebemish** [comment]
Copying this information from discord: it is worth noting that constant values are *already in the published javadocs* (`constant-values.html`, which every constant field entry links to)

**Review by IotaBread — APPROVED** [review]

**Pull request merged**
