### PR TITLE
Mention the versions API in readme.

### PR DESCRIPTION
**Pull request by mk-pmb**
Thanks again, @FirstMegaGame4 , for your solution over in https://github.com/QuiltMC/quiltmc.org/issues/229 .

### CODE REVIEW

**Review by supersaiyansubtlety — APPROVED** [review]

**Review by eristhea — APPROVED** [review]
would you mind also updating the link to the import tool to be the one on quiltmc.org?

**Comment by mk-pmb** [comment]
Amended it to point to the query for a specific Minecraft version, in hopes that this will reduce server load.

**Comment by mk-pmb** [comment]
I tried to update the import tool link, but I cannot determine whether the link caption "LambdAurora's import tool" is still correct, as the new target seems to not mention "LambdAurora".

**Comment by supersaiyansubtlety** [comment]
iirc the new one is by simpledemon
but since it's on the quilt site it's probably ok to just say "quilt import tool"

**Comment by mk-pmb** [comment]
I updated the commit and also separated the URLs from the text in order to reduce future diff noise if the URLs change again.

⚠ An attribution has been removed. Maintainers should verify this before merging, especially if the tool's license may require attribution.

**Review by eristhea — APPROVED** [review]
I didn't know you could do that in markdown

**Review by OroArmor — APPROVED** [review]

**Review by IotaBread — APPROVED** [review]

**Pull request merged**
