### PR TITLE
Add new JavaDoc generation

### LINKED ISSUE #33: Reworking how JavaDoc generation is done
Currently javadocs are broken due to compilation errors and the tools used to make these javadocs are unstable. Recently @ByMartrixx created draftsman as a project that strips code from a jar, allowing it to be recompiled. A pull request should be opened reimplementing the features as they currently stand.

### PR DESCRIPTION
**Pull request by IotaBread**
Closes #33. Updates required java to 17 because that's what Minecraft uses, and we need to recompile it (kinda). Removes dependency on MappingPoet, everything used has been moved, but I haven't implemented namespace tables yet

### CODE REVIEW

**Comment by OroArmor** [comment]
@LambdAurora what is your opinion on the namespace table? Tbh I don't think it has much use, but I've never really touched the javadocs extensively

**Comment by LambdAurora** [comment]
> @LambdAurora what is your opinion on the namespace table? Tbh I don't think it has much use, but I've never really touched the javadocs extensively

imo it should stay, if I read the Javadoc and need the intermediary name, I don't want to have to like go talk to a bot.

**Comment by IotaBread** [comment]
image
Namespace tables have been implemented

**Review by OroArmor — APPROVED** [review]

**Comment by OroArmor** [comment]
@LambdAurora can you review this? want to merge it in

**Pull request merged**
