### PR TITLE
Add decompiler API

### LINKED ISSUE #35: Add a decompiler API to the buildscript.
Currently only CFR is used to decompile code. Because of the improvements in quiltflower, adding a way to have multiple decompilers would be nice.

### PR DESCRIPTION
**Pull request by IotaBread**
Adds Quiltflower, allows setting decompiler options from the buildscript, allows making decompile tasks for any jar. Closes #35

Eventually would also ease incorporation of [Draftsman](https://github.com/QuiltMC/javadoc-draftsman) to replace Mapping Poet

### CODE REVIEW

**Comment by OroArmor** [comment]
Looks good so far, but there is no way to add javadocs to the output code. Not 100% sure how this is handled in Loom, but whatever fake source we create needs this feature.

**Comment by IotaBread** [comment]
I forgot to add that, I don't know if CFR has support for it.

**Comment by IotaBread** [comment]
I added javadoc support for QF, CFR still needs implementing

**Comment by IotaBread** [comment]
@OroArmor now it can add javadocs to the output code

**Review by OroArmor — APPROVED** [review]

**Review by LambdAurora — APPROVED** [review]

**Pull request merged**
