### PR TITLE
Rework Javadoc styling entirely to be Quilt-themed.

### PR DESCRIPTION
**Pull request by LambdAurora**
It contains a light and dark theme.

I also reverted lot of Javadoc's font stuff because it's just unreadable.

Here's a preview of how it looks:
image
image

There might be some missing stuff, hopefully it can be found quickly.

### CODE REVIEW

**Review by OroArmor — APPROVED** [review]

**Review by Leo40Git — APPROVED** [review]

**Review by supersaiyansubtlety — APPROVED** [review]

**Review by IotaBread — APPROVED** [review]
The white search bar in the dark theme kinda bothers me a bit... it could be changed to something more fitting? Aside from that looks good to me

**Comment by LambdAurora** [comment]
> The white search bar in the dark theme kinda bothers me a bit... it could be changed to something more fitting? Aside from that looks good to me

I honestly thought about that but I'm a bit worried of what it'll require so I'm keeping it for later.

**Comment by IotaBread** [comment]
Wouldn't something like this work?
```css
nav input {
    background-color: var(--quilt_theme_background);
    color: var(--quilt_theme_foreground)
}
```

**Comment by LambdAurora** [comment]
No because this CSS is incredibly annoying to edit, it wants super precise selectors as it has a tendency of overriding bunch of default values.

**Comment by IotaBread** [comment]
Ah, it's fine then

**Comment by LambdAurora** [comment]
Good news @ByMartrixx!

The styling now applies to the search stuff too.
image

**Comment by IotaBread** [comment]
Great!

**Pull request merged**
