### PR TITLE
consolidate registry package and improve registry/tag mappings

### PR DESCRIPTION
**Pull request by eristhea**
this pr does four things:
1. implements yarn's [great registry repackaging](https://gist.github.com/apple502j/1bc2dd67fe7e055d9be5d00fa0c04fbe#great-registry-repackaging) to keep all registry packages in one place
2. names all tags. Many tags have been named differently from their filenames, which could cause confusion, but increases clarity in code. Please provide feedback on this change!
3. names all registries. Most registries match what they used to be in 1.19.2.
4. does miscellaneous new mappings, all confined to the registry package

### CODE REVIEW

**Review by OroArmor — APPROVED** [review]

**Comment by eristhea** [comment]
this may still get some big changes; I'm planning on reading through all the files again tomorrow to make sure all the names are good

**Comment by LambdAurora** [comment]
What's the reasoning for having the tag package in the registry package?

**Comment by eristhea** [comment]
The same reasoning as yarn had. Tags are all registry-based, so putting them in the registry package is a good reflection of how they work internally.

**Review by NoComment1105 — APPROVED** [review]
Far better than what I produced 😅

**Comment by eristhea** [comment]
second check over complete; I'm comfortable with putting the ix0rai seal of approval :tm: on this!

**Pull request merged**
