### PR TITLE
screen handler mappings, 1.19 edition

### PR DESCRIPTION
**Pull request by eristhea**
oro was not satisfied with #397, so I had to do this
this is a copy of #397 to be merged alongside it, please review there and I'll keep it synced!

### CODE REVIEW

**Comment by EnnuiL** [comment]
i'm confused, it looks like the same picture as #397; maybe the target was wrong?

**Comment by eristhea** [comment]
oh, my mistake
I'll fix the target

**Review by EnnuiL — APPROVED** [review]

**Comment by Mysterious-Dev** [comment]
That's weird, why the target branch is for 1.20 version ?

**Comment by NoComment1105** [comment]
Maybe i shouldn't have update based, two seconds please

**Comment by NoComment1105** [comment]
Sorted, thankfully there were no conflicts

**Pull request closed without merging**
